# Форматы описания систем координат {#manual-crs}

В современной практике работы с ГИС применяется три основных формата описания систем координат:

* Текстовое описание в формате **Well-Known Text (WKT)**;
* Текстовое описание в формате строки **PROJ**;
* Код (индекс) системы координат в одной из широко используемых баз данных — EPSG, ESRI, IAU, SpatialReference.org

Формат **PROJ** — один из трёх стандартных форматов описания систем координат, был предложен разработчиками библиотеки [PROJ](https://proj.org/), используемой для преобразования систем координат пространственных данных (отсюда и название формата). Часто этот формат называют также PROJ.4, поскольку он был введен в 4-й версии библиотеки PROJ. Другой формат — коды [**EPSG**](http://www.epsg-registry.org/) (удобный ресурс для поиска — [epsg.io](https://epsg.io/)), введённые в оборот для быстрого доступа к наиболее распространенным системам координат. Третий вариант — формат **Well-Known Text (WKT)**, который предоставляет наиболее полные возможности для описания параметров системы координат. Формат WKT является [международным стандартом](https://www.iso.org/standard/76496.html). Ознакомиться с его определением можно на [сайте](http://docs.opengeospatial.org/is/18-010r7/18-010r7.html) Open Geospatial Consortium.